[package]
name = "day01"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
criterion = "0.4"

[[bench]]
name = "total_distance"
harness = false

[[bench]]
name = "similarity_score"
harness = false
